server:
  port: 8080
  servlet:
    context-path:


spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      # 启用
      enabled: true
      # 上传文件单个限制
      max-file-size: 5MB
      # 总限制
      max-request-size: 6MB
  datasource:
    userdb:
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/userdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false

    goodsdb:
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/goodsdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false

    orderdb:
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/orderdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false

  redis:
    host: 120.26.69.124
    port: 6379
    password:

  rabbitmq:
    host: 120.26.69.124
    port: 5672
    username: admin
    password: admin
    virtual-host: /

  elasticsearch:
    rest:
      uris: 120.26.69.124:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
jgs:
  cat:
    name: cat
    phone: 13700000000
    email: cat@163.com
    address: beijing